### ISSUE TITLE
TODO: Sprint 2

### ISSUE THREAD

**Issue by pabloazurduy** [pabloazurduy/vrp-wareclouds#4]
- [x] Probar alternativa función objetivo no lineal (costo por ruta más importante que suma de costos), costo por ruta mala (?)
- [x] castigar distancia de comunas en el mismo cluster (pares de variables)
- [x] revisar `big M`
- [x] revisar libro daganzo (?)

Part 2 
- simular datos de una tasa de aceptación: cómo calcular los beta en base a eso ?
- [x] IP(aceptar(c)) , dado ese dataset cómo estimar los beta de la función objetivo **

**Comment by pabloazurduy** [comment]
closed separation on other issues
